# Generated by Django 3.1.2 on 2020-10-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName_text', models.CharField(max_length=20)),
                ('inventoryQuantity_int', models.IntegerField()),
                ('itemPrice_decimal', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=200)),
                ('password_text', models.CharField(max_length=200)),
                ('firstName_text', models.CharField(max_length=200)),
                ('lastName_text', models.CharField(max_length=200)),
                ('email_email', models.EmailField(max_length=200)),
                ('phoneNumber_text', models.CharField(max_length=200)),
                ('accountBalance_decimal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('accountType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dansbagels.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpTime', models.DateTimeField()),
                ('currentStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dansbagels.orderstatus')),
                ('menuItems', models.ManyToManyField(to='dansbagels.MenuItem')),
                ('personOrdered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dansbagels.person')),
            ],
        ),
    ]
