# Generated by Django 3.1.2 on 2020-10-17 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dansbagels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menuItems',
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderQuantity_int', models.IntegerField()),
                ('itemOrdered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dansbagels.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dansbagels.order')),
            ],
        ),
    ]
