# Generated by Django 3.0.3 on 2020-02-24 17:00

from django.db import migrations
from django.utils import timezone
from datetime import datetime
import pytz

def populate_db(apps, schema_editor):
    """
    This is a new function that I define myself.  It takes two parameters.

    The first parameter `apps` is an application registry which enables access
    to my models without needing to use the import statement.  The details are
    a bit involved, but the application registry lets me access previous
    versions of my models; importing the classes via the import statement would
    only let me use those classes as they exist right now.

    The second parameter `schema_editor` may be used when I change the layout
    of fields in a model.  Since we are only interested in creating new
    records right now, we can ignore it.
    """

    print(" ")

    Person = apps.get_model('dansbagels', 'Person')
    AccountType = apps.get_model('dansbagels', 'AccountType')

    print("Adding all existing customers")

    person0 = Person()
    person0.firstName_text = "Arthur"
    person0.lastName_text = "Dent"
    person0.username_text = "ArthurDent"
    person0.password_text = "default"
    person0.email_email = "a.Dent@hgtg.com"
    person0.phoneNumber_text = "2819635306"
    person0.accountBalance_decimal = "100.00"
    person0.accountType = (AccountType.objects.get(pk=1))
    person0.save()

    person1 = Person()
    person1.firstName_text = "Abe"
    person1.lastName_text = "Lincoln"
    person1.username_text = "AbeLincoln"
    person1.password_text = "default"
    person1.email_email = "abeLink@thewhitehouse.gov"
    person1.phoneNumber_text = "1159168395"
    person1.accountBalance_decimal = "100.00"
    person1.accountType = (AccountType.objects.get(pk=1))
    person1.save()

    person2 = Person()
    person2.firstName_text = "Ashley"
    person2.lastName_text = "Stinson"
    person2.username_text = "AshleyStinson"
    person2.password_text = "default"
    person2.email_email = "StAsh607@bagelLover.com"
    person2.phoneNumber_text = "4041342472"
    person2.accountBalance_decimal = "100.00"
    person2.accountType = (AccountType.objects.get(pk=1))
    person2.save()

    person3 = Person()
    person3.firstName_text = "SlartiBartFast"
    person3.lastName_text = "NULL"
    person3.username_text = "SlartiBartFastNULL"
    person3.password_text = "default"
    person3.email_email = "NorwayRules@hgtg.com"
    person3.phoneNumber_text = "9197188025"
    person3.accountBalance_decimal = "100.00"
    person3.accountType = (AccountType.objects.get(pk=1))
    person3.save()

    person4 = Person()
    person4.firstName_text = "MuhryeUh"
    person4.lastName_text = "Reynolds"
    person4.username_text = "MuhryeUhReynolds"
    person4.password_text = "default"
    person4.email_email = "mary@notyourLover.com"
    person4.phoneNumber_text = "5052361009"
    person4.accountBalance_decimal = "100.00"
    person4.accountType = (AccountType.objects.get(pk=1))
    person4.save()

    person5 = Person()
    person5.firstName_text = "Sheldon"
    person5.lastName_text = "Cooper"
    person5.username_text = "SheldonCooper"
    person5.password_text = "default"
    person5.email_email = "Sheldon.Cooper@tbbt.com"
    person5.phoneNumber_text = "1018936041"
    person5.accountBalance_decimal = "100.00"
    person5.accountType = (AccountType.objects.get(pk=1))
    person5.save()

    person6 = Person()
    person6.firstName_text = "Janie"
    person6.lastName_text = "Dhoe"
    person6.username_text = "JanieDhoe"
    person6.password_text = "default"
    person6.email_email = "notyouraverageJane@electronicmail.com"
    person6.phoneNumber_text = "4136399522"
    person6.accountBalance_decimal = "100.00"
    person6.accountType = (AccountType.objects.get(pk=1))
    person6.save()

    person7 = Person()
    person7.firstName_text = "Ben"
    person7.lastName_text = "Smith"
    person7.username_text = "BenSmith"
    person7.password_text = "default"
    person7.email_email = "B.Smith@sumRandom.com"
    person7.phoneNumber_text = "8470106021"
    person7.accountBalance_decimal = "100.00"
    person7.accountType = (AccountType.objects.get(pk=1))
    person7.save()

    person8 = Person()
    person8.firstName_text = "Gwynnifer"
    person8.lastName_text = "Beetlejuice"
    person8.username_text = "GwynniferBeetlejuice"
    person8.password_text = "default"
    person8.email_email = "heyitsGwyn@gwynb.com"
    person8.phoneNumber_text = "8204045476"
    person8.accountBalance_decimal = "100.00"
    person8.accountType = (AccountType.objects.get(pk=1))
    person8.save()

    person9 = Person()
    person9.firstName_text = "Collin"
    person9.lastName_text = "Miller"
    person9.username_text = "CollinMiller"
    person9.password_text = "default"
    person9.email_email = "collin.miller@msn.com"
    person9.phoneNumber_text = "3051142905"
    person9.accountBalance_decimal = "100.00"
    person9.accountType = (AccountType.objects.get(pk=1))
    person9.save()

    person10 = Person()
    person10.firstName_text = "Olivia"
    person10.lastName_text = "Garcia"
    person10.username_text = "OliviaGarcia"
    person10.password_text = "default"
    person10.email_email = "Olivia.Garc@widget.com"
    person10.phoneNumber_text = "4653364385"
    person10.accountBalance_decimal = "100.00"
    person10.accountType = (AccountType.objects.get(pk=1))
    person10.save()

    person11 = Person()
    person11.firstName_text = "Frodo"
    person11.lastName_text = "Baggins"
    person11.username_text = "FrodoBaggins"
    person11.password_text = "default"
    person11.email_email = "Frodo.Baggins@theShire.com"
    person11.phoneNumber_text = "1799862755"
    person11.accountBalance_decimal = "100.00"
    person11.accountType = (AccountType.objects.get(pk=1))
    person11.save()

    person12 = Person()
    person12.firstName_text = "Charles"
    person12.lastName_text = "Priest"
    person12.username_text = "CharlesPriest"
    person12.password_text = "default"
    person12.email_email = "c.priest@widget.com"
    person12.phoneNumber_text = "5223433658"
    person12.accountBalance_decimal = "100.00"
    person12.accountType = (AccountType.objects.get(pk=1))
    person12.save()

    person13 = Person()
    person13.firstName_text = "Mario"
    person13.lastName_text = "Theplumber"
    person13.username_text = "MarioTheplumber"
    person13.password_text = "default"
    person13.email_email = "mario@letsago.com"
    person13.phoneNumber_text = "8747583621"
    person13.accountBalance_decimal = "100.00"
    person13.accountType = (AccountType.objects.get(pk=1))
    person13.save()

    person14 = Person()
    person14.firstName_text = "Luigi"
    person14.lastName_text = "Theplumber"
    person14.username_text = "LuigiTheplumber"
    person14.password_text = "default"
    person14.email_email = "luigo@itsaluigi.com"
    person14.phoneNumber_text = "9992912615"
    person14.accountBalance_decimal = "100.00"
    person14.accountType = (AccountType.objects.get(pk=1))
    person14.save()

    person15 = Person()
    person15.firstName_text = "Flynn"
    person15.lastName_text = "Taggart"
    person15.username_text = "FlynnTaggart"
    person15.password_text = "default"
    person15.email_email = "Flynn.T@Doom.com"
    person15.phoneNumber_text = "9926911263"
    person15.accountBalance_decimal = "100.00"
    person15.accountType = (AccountType.objects.get(pk=1))
    person15.save()

    person16 = Person()
    person16.firstName_text = "Winnie"
    person16.lastName_text = "ThePoo"
    person16.username_text = "WinnieThePoo"
    person16.password_text = "default"
    person16.email_email = "mrwinnie@ohbother.net"
    person16.phoneNumber_text = "7904514746"
    person16.accountBalance_decimal = "100.00"
    person16.accountType = (AccountType.objects.get(pk=1))
    person16.save()

    person17 = Person()
    person17.firstName_text = "Darth"
    person17.lastName_text = "Vader"
    person17.username_text = "DarthVader"
    person17.password_text = "default"
    person17.email_email = "immadaddy@georgelucas.org"
    person17.phoneNumber_text = "7026881314"
    person17.accountBalance_decimal = "100.00"
    person17.accountType = (AccountType.objects.get(pk=1))
    person17.save()

    person18 = Person()
    person18.firstName_text = "Ron"
    person18.lastName_text = "Burgandy"
    person18.username_text = "RonBurgandy"
    person18.password_text = "default"
    person18.email_email = "theburg@imanachor.com"
    person18.phoneNumber_text = "5503924089"
    person18.accountBalance_decimal = "100.00"
    person18.accountType = (AccountType.objects.get(pk=1))
    person18.save()

    person19 = Person()
    person19.firstName_text = "Tony"
    person19.lastName_text = "Stark"
    person19.username_text = "TonyStark"
    person19.password_text = "default"
    person19.email_email = "iamironman@avengers.com"
    person19.phoneNumber_text = "5993751992"
    person19.accountBalance_decimal = "100.00"
    person19.accountType = (AccountType.objects.get(pk=1))
    person19.save()

    person20 = Person()
    person20.firstName_text = "Thor"
    person20.lastName_text = "Odinson"
    person20.username_text = "ThorOdinson"
    person20.password_text = "default"
    person20.email_email = "strongestavenger@avengers.com"
    person20.phoneNumber_text = "2526405332"
    person20.accountBalance_decimal = "100.00"
    person20.accountType = (AccountType.objects.get(pk=1))
    person20.save()

    person21 = Person()
    person21.firstName_text = "Willy"
    person21.lastName_text = "Wonka"
    person21.username_text = "WillyWonka"
    person21.password_text = "default"
    person21.email_email = "sillywilly@thechocofactory.com"
    person21.phoneNumber_text = "5683954945"
    person21.accountBalance_decimal = "100.00"
    person21.accountType = (AccountType.objects.get(pk=1))
    person21.save()

    person22 = Person()
    person22.firstName_text = "John"
    person22.lastName_text = "McClane"
    person22.username_text = "JohnMcClane"
    person22.password_text = "default"
    person22.email_email = "john@yippeKiYay.com"
    person22.phoneNumber_text = "2515517615"
    person22.accountBalance_decimal = "100.00"
    person22.accountType = (AccountType.objects.get(pk=1))
    person22.save()

    person23 = Person()
    person23.firstName_text = "Wally"
    person23.lastName_text = "Waldo"
    person23.username_text = "WallyWaldo"
    person23.password_text = "default"
    person23.email_email = "Waldo@wheresWaldo.com"
    person23.phoneNumber_text = "5217029026"
    person23.accountBalance_decimal = "100.00"
    person23.accountType = (AccountType.objects.get(pk=1))
    person23.save()

    person24 = Person()
    person24.firstName_text = "Joe"
    person24.lastName_text = "Johnson"
    person24.username_text = "JoeJohnson"
    person24.password_text = "default"
    person24.email_email = "youraveragejoe@widget.com"
    person24.phoneNumber_text = "879386074"
    person24.accountBalance_decimal = "100.00"
    person24.accountType = (AccountType.objects.get(pk=1))
    person24.save()

    print("\nDone adding all existing customers.")


class Migration(migrations.Migration):

    dependencies = [
        ('dansbagels', '0003_populate_AccountType'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
