# Generated by Django 3.0.3 on 2020-02-24 17:00

from django.db import migrations
from django.utils import timezone
from datetime import datetime
import pytz

def populate_db(apps, schema_editor):
    """
    This is a new function that I define myself.  It takes two parameters.

    The first parameter `apps` is an application registry which enables access
    to my models without needing to use the import statement.  The details are
    a bit involved, but the application registry lets me access previous
    versions of my models; importing the classes via the import statement would
    only let me use those classes as they exist right now.

    The second parameter `schema_editor` may be used when I change the layout
    of fields in a model.  Since we are only interested in creating new
    records right now, we can ignore it.
    """

    print(" ")

    MenuItem = apps.get_model('dansbagels', 'MenuItem')

    print("Adding all menu items")

    item0 = MenuItem()
    item0.itemName_text = "Plain Bagel"
    item0.inventoryQuantity_int = 115
    item0.itemPrice_decimal = 2.00
    item0.save()

    item1 = MenuItem()
    item1.itemName_text = "Onion Bagel"
    item1.inventoryQuantity_int = 142
    item1.itemPrice_decimal = 2.00
    item1.save()

    item2 = MenuItem()
    item2.itemName_text = "Cinnamon Raisin Bagel"
    item2.inventoryQuantity_int = 201
    item2.itemPrice_decimal = 2.00
    item2.save()

    item3 = MenuItem()
    item3.itemName_text = "Sesame Bagel"
    item3.inventoryQuantity_int = 243
    item3.itemPrice_decimal = 2.00
    item3.save()

    item4 = MenuItem()
    item4.itemName_text = "Cheesy Bagel"
    item4.inventoryQuantity_int = 81
    item4.itemPrice_decimal = 2.00
    item4.save()

    item5 = MenuItem()
    item5.itemName_text = "Pumpernickel Bagel"
    item5.inventoryQuantity_int = 233
    item5.itemPrice_decimal = 2.00
    item5.save()

    item6 = MenuItem()
    item6.itemName_text = "Plain Smear"
    item6.inventoryQuantity_int = 69
    item6.itemPrice_decimal = 1.00
    item6.save()

    item7 = MenuItem()
    item7.itemName_text = "Honey Nut Smear"
    item7.inventoryQuantity_int = 59
    item7.itemPrice_decimal = 1.00
    item7.save()

    item8 = MenuItem()
    item8.itemName_text = "Strawberry Smear"
    item8.inventoryQuantity_int = 90
    item8.itemPrice_decimal = 1.00
    item8.save()

    item9 = MenuItem()
    item9.itemName_text = "French Onion Smear"
    item9.inventoryQuantity_int = 5
    item9.itemPrice_decimal = 1.00
    item9.save()

    item10 = MenuItem()
    item10.itemName_text = "+ Bacon"
    item10.inventoryQuantity_int = 65
    item10.itemPrice_decimal = 1.00
    item10.save()

    item11 = MenuItem()
    item11.itemName_text = "+ Egg"
    item11.inventoryQuantity_int = 146
    item11.itemPrice_decimal = 2.00
    item11.save()

    item12 = MenuItem()
    item12.itemName_text = "+ Cheese"
    item12.inventoryQuantity_int = 231
    item12.itemPrice_decimal = 1.00
    item12.save()

    item13 = MenuItem()
    item13.itemName_text = "+ Sausage"
    item13.inventoryQuantity_int = 4
    item13.itemPrice_decimal = 2.00
    item13.save()

    item14 = MenuItem()
    item14.itemName_text = "+ Avacado"
    item14.inventoryQuantity_int = 51
    item14.itemPrice_decimal = 10.00
    item14.save()

    item15 = MenuItem()
    item15.itemName_text = "+ Turkey"
    item15.inventoryQuantity_int = 78
    item15.itemPrice_decimal = 2.00
    item15.save()

    item16 = MenuItem()
    item16.itemName_text = "+ Ham"
    item16.inventoryQuantity_int = 250
    item16.itemPrice_decimal = 2.00
    item16.save()

    item17 = MenuItem()
    item17.itemName_text = "+ Spinach"
    item17.inventoryQuantity_int = 283
    item17.itemPrice_decimal = 1.00
    item17.save()

    item18 = MenuItem()
    item18.itemName_text = "+ Tomato"
    item18.inventoryQuantity_int = 245
    item18.itemPrice_decimal = 1.00
    item18.save()

    item19 = MenuItem()
    item19.itemName_text = "+ Lox"
    item19.inventoryQuantity_int = 44
    item19.itemPrice_decimal = 10.00
    item19.save()

    item20 = MenuItem()
    item20.itemName_text = "Coffee"
    item20.inventoryQuantity_int = 278
    item20.itemPrice_decimal = 2.00
    item20.save()

    item21 = MenuItem()
    item21.itemName_text = "Milk"
    item21.inventoryQuantity_int = 65
    item21.itemPrice_decimal = 2.00
    item21.save()

    item22 = MenuItem()
    item22.itemName_text = "Orange Juice"
    item22.inventoryQuantity_int = 1
    item22.itemPrice_decimal = 2.00
    item22.save()

    item23 = MenuItem()
    item23.itemName_text = "Water"
    item23.inventoryQuantity_int = 121
    item23.itemPrice_decimal = 5.00
    item23.save()


    print("\nDone adding all menu items")


class Migration(migrations.Migration):

    dependencies = [
        ('dansbagels', '0004_populate_Person'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
