# Generated by Django 3.1.2 on 2020-11-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dansbagels', '0007_auto_20201104_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderInstructions_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
