# Generated by Django 3.1.2 on 2020-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dansbagels', '0009_order_ordercost_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='orderStatus_text',
            field=models.CharField(choices=[(1, 'Ordered'), (2, 'In Preparation'), (3, 'Ready'), (4, 'Completed')], max_length=20),
        ),
    ]
